FROM rust:1.82-bookworm
RUN apt-get update
RUN apt-get install -y build-essential llvm libclang-dev
# 安装基础依赖
RUN apt-get install -y curl ca-certificates

# 下载并安装VS Code Server
RUN curl -fsSL https://code.visualstudio.com/sha/download?build=stable -o vscode-server.tar.gz \
 && mkdir -p /usr/local/bin/code-server \
 && tar -xzf vscode-server.tar.gz -C /usr/local/bin/code-server --strip-components=1 \
 && rm vscode-server.tar.gz

# 配置VS Code Server
RUN echo '#!/bin/sh' > /usr/local/bin/code-server \
 && echo '/usr/local/bin/code-server/bin/code-server --no-sandbox --host 0.0.0.0 --port 8080' >> /usr/local/bin/code-server \
 && chmod +x /usr/local/bin/code-server

# 使用ENTRYPOINT启动VS Code Server
ENTRYPOINT ["/usr/local/bin/code-server"]
#容器中安装ssh
RUN apt-get install -y openssh-server
RUN mkdir -p /var/run/sshd
RUN mkdir -p /root/.ssh
#
RUN echo "root:aHGlkfh!81!@736" | chpasswd
RUN sed -ri 's/session requiredpam_loginuid.so/#session required pam_loginuid.so/g' /etc/pam.d/sshd
RUN sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/g" /etc/ssh/sshd_config
# 把做好的authorized_keys拷到容器内authorized_keys中去
ADD authorized_keys /root/.ssh/authorized_keys
ADD  run.sh  /run.sh
RUN  chmod  755 /run.sh
EXPOSE  22
# 使用ENTRYPOINT启动VS Code Server
ENTRYPOINT ["/usr/local/bin/code-server"]
