FROM rust:1.82-bookworm
RUN apt-get update
RUN apt-get install -y build-essential llvm libclang-dev
#容器中安装ssh
RUN apt-get install -y openssh-server
RUN mkdir -p /var/run/sshd
RUN mkdir -p /root/.ssh
#
RUN echo "root:123456" | chpasswd
RUN sed -ri 's/session requiredpam_loginuid.so/#session required pam_loginuid.so/g' /etc/pam.d/sshd
RUN sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/g" /etc/ssh/sshd_config
# 把做好的authorized_keys拷到容器内authorized_keys中去
ADD authorized_keys /root/.ssh/authorized_keys
ADD  run.sh  /run.sh
RUN  chmod  755 /run.sh
EXPOSE  22
ENV RUSTUP_HOME=/usr/local/rustup
ENV RUST_VERSION=1.82.0
ENV CARGO_HOME=/usr/local/cargo
ENV PATH=/usr/local/cargo/bin:$PATH

# 创建或修改.cargo/config.toml文件，设置镜像源为清华大学
Add config.toml $HOME/.cargo/config.toml

#容器启动后直接执行
CMD  ["/run.sh"]
